using Fridge.Models;

namespace Fridge.Migrations
{
    using System.Data.Entity.Migrations;

    internal sealed partial class Configuration
    {
        /// <summary>
        /// Automatic data migration for the Ingredient table
        /// </summary>
        /// <param name="context"> The database connection </param>
        public void Ingredient(ApplicationDbContext context)
        {
            context.Ingredients.AddOrUpdate(i => i.Name,
             new Ingredient() { Name = "Fusilli", Price = 1.20m, Quantity = 500, Unit = "gram", CategoryId = 1, Description = "Pasta van durum tarwegriesmeel." },
             new Ingredient() { Name = "Lasagnabladen", Price = 1.10m, Quantity = 250, Unit = "gram", CategoryId = 1, Description = "Pasta van durum tarwegriesmeel." },
             new Ingredient() { Name = "Macaroni", Price = 1.45m, Quantity = 500, Unit = "gram", CategoryId = 1, Description = "Het ideale (basis)ingrediënt voor een pastagerecht (warm of koud) met saus, groenten, vlees of vis." },
             new Ingredient() { Name = "Spaghetti", Price = 1.05m, Quantity = 500, Unit = "gram", CategoryId = 1, Description = "Met deze spaghetti maak je de lekkerste Italiaanse gerechten!" },
             new Ingredient() { Name = "Tortellini", Price = 1.15m, Quantity = 440, Unit = "gram", CategoryId = 1, Description = "Creëer in een handomdraai een lekker Italiaans gerecht met deze deegringetjes gevuld met kaas." },
             new Ingredient() { Name = "Aardappelen", Price = 2.50m, Quantity = 1, Unit = "kg", CategoryId = 2, Description = "Iets kruimige aardappelen zijn na het koken stevig in de kern en aan de buitenkant kruimig en los van structuur. Het is een veelzijdige aardappel waar je bijna alle aardappelgerechten mee kunt maken. Ook in schil te bereiden." },
             new Ingredient() { Name = "Bloemkool", Price = 2.30m, Quantity = 1, Unit = "stuks", CategoryId = 2, Description = "Bloemkool is nog altijd één van de meest gegeten groente in Nederland. De Nederlandse bloemkool is heerlijk om te koken, of om te gebruiken in een soep, om te wokken of in een stamppot. Elke dag vers van onze teler." },
             new Ingredient() { Name = "Broccoli", Price = 1.35m, Quantity = 500, Unit = "gram", CategoryId = 2, Description = "Broccoli heeft een knapperige, frisse iets pittigere smaak dan bloemkool. Heerlijk gekookt of in kleine roosjes door de roerbak heen. Tip: ook lekker om rauw te snacken bij de borrel." },
             new Ingredient() { Name = "Boerenkool", Price = 1.60m, Quantity = 150, Unit = "gram", CategoryId = 2, Description = "Boerenkool om een echte Hollandse stamppot mee te maken. Lekker met gebakken spekjes en een rookworst. Of als ingrediënt in een hartige taart, door de pasta met bijv. geitenkaas of in een smoothie met banaan en mango?" },
             new Ingredient() { Name = "Bruine bonen", Price = 1, Quantity = 720, Unit = "gram", CategoryId = 2, Description = "bruine bonen zijn lekker en gezond. Boordevol vezels en eiwitten en ideaal om mee te variëren. Lekker op traditionele wijze met aardappels en vlees, maar ook als chili, bonensoep of door een salade." },
             new Ingredient() { Name = "Champignons", Price = 1.20m, Quantity = 250, Unit = "gram", CategoryId = 2, Description = "De witte champignon wordt gekenmerkt door zijn gelijkmatige, witte ronde hoed en witte steel." },
             new Ingredient() { Name = "Courgette", Price = 1.10m, Quantity = 1, Unit = "stuk", CategoryId = 2, Description = "De courgette heeft een frisse, zachte, redelijk neutrale smaak. Je kan een courgette in vele verschillende gerechten gebruiken, bijvoorbeeld in sauzen, roerbakschotels of bij pastagerechten.Tip: probeer ook eens gegrild uit de oven of van de bbq." },
             new Ingredient() { Name = "Komkommer", Price = 1.15m, Quantity = 1, Unit = "stuk", CategoryId = 2, Description = "Komkommer heeft een frisse, knapperige, neutrale smaak. Heerlijk door een salade of als gezonde snack." },
             new Ingredient() { Name = "Paprika", Price = 1.05m, Quantity = 1, Unit = "stuk", CategoryId = 2, Description = "De rode paprika is wat zoeter van smaak dan de groene variant. Daarom is deze ideaal om te gebruiken voor een verse pastasaus of een gezonde salade. Tip: probeer de rode paprika ook eens te grillen of gevuld uit de oven." },
             new Ingredient() { Name = "Prei", Price = 1.30m, Quantity = 1, Unit = "stuk", CategoryId = 2, Description = "Prei is een kruidachtige plant met een karakteristieke geur. De enigszins lange stengels zijn wit tot lichtgroen, het blad is donkergroen. Prei behoort tot de lookfamilie waartoe ook ui, bieslook en knoflook behoren." },
             new Ingredient() { Name = "Spinazie", Price = 2.40m, Quantity = 400, Unit = "gram", CategoryId = 2, Description = "Spinazie om te (roer)bakken met een uitje, in de salade, stamppot of in een hartige taart. Met spinazie kun je echt eindeloos combineren. Extra handig! Deze spinazie is al gewassen en dus direct klaar voor gebruik." },
             new Ingredient() { Name = "Spruitjes", Price = 2.20m, Quantity = 350, Unit = "gram", CategoryId = 2, Description = "Spruitjes zijn echte herfst- en wintergroenten. Het is een veelzijdig mini kooltje die je op heel veel verschillende manieren kan klaar maken. Elke dag vers van onze teler." },
             new Ingredient() { Name = "Taugé", Price = 1.45m, Quantity = 125, Unit = "gram", CategoryId = 2, Description = "Vers verpakt, 125 gram. Taugé heeft een neutrale, iets stroeve smaak. Roerbak of kook taugé nooit langer dan 1 minuut." },
             new Ingredient() { Name = "Tomaat", Price = 1.20m, Quantity = 250, Unit = "gram", CategoryId = 2, Description = "De zoete en sappige cherrytomaten zijn heerlijk door een verse salade of gewoon als gezonde snack." },
             new Ingredient() { Name = "Ui", Price = 1.05m, Quantity = 2, Unit = "stuks", CategoryId = 2, Description = "Uien behoren tot de familie van de uiachtigen, evenals prei en knoflook." },
             new Ingredient() { Name = "Witlof", Price = 2.60m, Quantity = 5, Unit = "stuks", CategoryId = 2, Description = "Witlof heeft een frisse, licht bittere smaak. Heerlijk gekookt, uit de oven of rauw door een gezonde salade." },
             new Ingredient() { Name = "Witte bonen", Price = 1, Quantity = 800, Unit = "gram", CategoryId = 2, Description = "Witte bonen in 40% tomatensaus" },
             new Ingredient() { Name = "Wortel", Price = 1.10m, Quantity = 500, Unit = "gram", CategoryId = 2, Description = "Na de oogst worden de worteltjes onmiddellijk geselecteerd en zorgvuldig geschrapt. Vervolgens worden de worteltjes gewassen en meteen verpakt. Zo behouden de worteltjes hun smaak en voedingswaarde." },
             new Ingredient() { Name = "Zuurkool", Price = 1.50m, Quantity = 520, Unit = "gram", CategoryId = 2, Description = "Witte kool wordt ontdaan van buitenblad, schoongemaakt, fijngesneden en bestrooid met zout (ongeveer 1,5%). Daarna gaat de gesneden kool spontaan gisten: zetmeel en andere koolhydraten worden door melkzuurbacteriën omgezet in melkzuur." },
             new Ingredient() { Name = "Aardbei", Price = 4, Quantity = 500, Unit = "gram", CategoryId = 3, Description = "Aardbeien zijn al eeuwen de meest geprezen zachte fruitsoort. Ze worden ook wel zomerkoninkjes genoemd. De aardbei is eigenlijk geen vrucht maar een schijnvrucht, de pitjes aan de buitenkant zijn de eigenlijke vruchtjes. Aardbeien zijn er in vele variëteiten waarbij grootte en kleur niets zeggen over de kwaliteit." },
             new Ingredient() { Name = "Ananas", Price = 1.20m, Quantity = 1, Unit = "stuk", CategoryId = 3, Description = "Deze ananas is fantastisch in een fruitsalade, een frisse smoothie en zelfs in warme maaltijden." },
             new Ingredient() { Name = "Appel", Price = 3.40m, Quantity = 4, Unit = "stuks", CategoryId = 3, Description = "Pink lady is een volzoet en aromatisch handappeltje met hard, stevig en zeer knapperig vruchtvlees. Ook ideaal om te bakken of in een salade." },
             new Ingredient() { Name = "Avocado", Price = 1.20m, Quantity = 1, Unit = "stuk", CategoryId = 3, Description = "Avocado is een zachte en romige vrucht. Lekker in een salade of op brood. Avocado is het hoofdingredient voor het maken van verse guacamole." },
             new Ingredient() { Name = "Banaan", Price = 1.80m, Quantity = 5, Unit = "stuks", CategoryId = 3, Description = "De banaan is de bekendste tropische fruitsoort. Bananen worden onrijp geoogst en in Nederland verder gerijpt in speciale rijpingskamers. Dit zorgt voor een goede kwaliteit en een heerlijke smaak. Lekker in smoothies, fruitsalade of als gezond tussendoortje." },
             new Ingredient() { Name = "Blauwe bessen", Price = 3, Quantity = 150, Unit = "gram", CategoryId = 3, Description = "Blauwe besssen hebben een fris zoete smaak en knapperige bite. Blauwe bessen kunnen uit de hand gegeten worden als gezonde snack. Maar ze zijn ook heerlijk door de yoghurt of in een smoothie." },
             new Ingredient() { Name = "Citroen", Price = 1.10m, Quantity = 5, Unit = "stuks", CategoryId = 3, Description = "Citroenen hebben een frisse en zure smaak. Een smaakmaker in zowel hartige als zoete gerechten." },
             new Ingredient() { Name = "Kiwi", Price = 1.30m, Quantity = 4, Unit = "stuks", CategoryId = 3, Description = "Zespri Organic Green groeit in harmonie met de natuur." },
             new Ingredient() { Name = "Mandarijn", Price = 2.25m, Quantity = 1, Unit = "kg", CategoryId = 3, Description = "Mandarijnen hebben een frisse en zoete smaak. Om zo uit de hand te eten of doe wat stukjes in de yoghurt met muesli of fruitsalade." },
             new Ingredient() { Name = "Meloen", Price = 2.30m, Quantity = 1, Unit = "stuk", CategoryId = 3, Description = "De Galiameloen is een sappige en zoete meloen. Lekker in een fruitsalade of in combinatie met parmaham." },
             new Ingredient() { Name = "Olijf", Price = 1.65m, Quantity = 240, Unit = "gram", CategoryId = 3, Description = "Deze Spaanse manzanilla olijven zonder pit zijn heerlijk door salades en op pizza's of om gewoon zo te eten." },
             new Ingredient() { Name = "Peer", Price = 2.05m, Quantity = 4, Unit = "stuks", CategoryId = 3, Description = "Conference is een sappige en veelzijdig peer. Een lekker peertje om zo te eten, voor in een taart of salade. Eet hem zoals jij het lekker vindt: stevig en fris of zoet en sappig als hij wat rijper is. Hoe zachter het vruchtvlees onderaan de steel is, hoe rijper de peer." },
             new Ingredient() { Name = "Perzik", Price = 3.10m, Quantity = 500, Unit = "gram", CategoryId = 3 },
             new Ingredient() { Name = "Pruim", Price = 1.10m, Quantity = 250, Unit = "gram", CategoryId = 3, Description = "Gewelde smaakvolle pruimen zonder pit. Om zo te eten, door de yoghurt maar ook bijvoorbeeld ook heerlijk als zoete touch in rijke stoofgerechten." },
             new Ingredient() { Name = "Boter", Price = 1, Quantity = 500, Unit = "gram", CategoryId = 4 },
             new Ingredient() { Name = "Boterham", Price = 1.05m, Quantity = 25, Unit = "stuks", CategoryId = 4, Description = "Boeren Bruinbrood" },
             new Ingredient() { Name = "Bouillon", Price = 1, Quantity = 8, Unit = "stuks", CategoryId = 4, Description = "Maggi Bouillon kip geeft je gerechten extra smaak." },
             new Ingredient() { Name = "Couscous", Price = 1.30m, Quantity = 400, Unit = "gram", CategoryId = 4, Description = "Wie houdt er niet van couscous? Het is snel, lekker, en heel makkelijk te combineren. Meng met bijvoorbeeld kruiden als ras el hanout en voeg ingrediënten toe die je lekker vindt. Denk aan aubergine, courgette, rozijnen, dadels, zongedroogde tomaatjes, olijven en feta." },
             new Ingredient() { Name = "Creme fraiche", Price = 1.10m, Quantity = 200, Unit = "gram", CategoryId = 4, Description = "room voor het verrijken van warme maaltijden" },
             new Ingredient() { Name = "Eieren", Price = 2.25m, Quantity = 10, Unit = "stuks", CategoryId = 4, Description = "Verpakking met 10 Scharreleieren klasse M" },
             new Ingredient() { Name = "Kaas", Price = 2, Quantity = 10, Unit = "stuks", CategoryId = 4, Description = "Lekker smeuïge Goudse jonge kaas gemaakt van 100% weidemelk. Natuurlijk lekker op de boterham of gewoon uit het vuistje. Tip! Beleg ook eens stokbroodje met een plakje van deze kaas en een fris schijfje komkommer." },
             new Ingredient() { Name = "Ketchup", Price = 1.10m, Quantity = 400, Unit = "ml", CategoryId = 4, Description = "Heinz Tomato ketchup is de welbekende ketchup gemaakt van echte Heinz tomaten." },
             new Ingredient() { Name = "Ketjap", Price = 2, Quantity = 500, Unit = "ml", CategoryId = 4, Description = "Ketjap is een zoete dikke, stroperige, zoete saus die wordt gebruikt in de Indonesische keuken. De saus is gemaakt van sojabonen. Om de saus de zoete authentieke Indonesische smaak te geven wordt er suiker aan toegevoegd." },
             new Ingredient() { Name = "Knoflook", Price = 1.15m, Quantity = 2, Unit = "stuks", CategoryId = 4, Description = "Knoflook is een echte smaakmaker die een gerecht extra smaak en geur geeft." },
             new Ingredient() { Name = "Mayonaise", Price = 1.05m, Quantity = 500, Unit = "ml", CategoryId = 4 },
             new Ingredient() { Name = "Melk", Price = 1.10m, Quantity = 1, Unit = "liter", CategoryId = 4, Description = "Verse halfvolle melk voor iedere dag. Een natuurlijke bron van calcium met het groene vinkje van het Voedingscentrum, oftewel een gezondere keuze!" },
             new Ingredient() { Name = "Olijfolie", Price = 4, Quantity = 500, Unit = "ml", CategoryId = 4, Description = "Olijfolie verkregen uit koude extractie. Verfijnd en zacht, voor bakken en braden." },
             new Ingredient() { Name = "Peper", Price = 2.10m, Quantity = 45, Unit = "gram", CategoryId = 4, Description = "Drogheria Alimentari zwarte peper komt uit Vietnam en zorgt voor een mooie pittige smaak." },
             new Ingredient() { Name = "Pinda's", Price = 2.25m, Quantity = 370, Unit = "gram", CategoryId = 4, Description = "Duyvis Pinda's zijn de klassiekers en op smaak gebracht met een beetje zout." },
             new Ingredient() { Name = "Rijst", Price = 1.05m, Quantity = 400, Unit = "gram", CategoryId = 4 },
             new Ingredient() { Name = "Sojasaus", Price = 2.10m, Quantity = 500, Unit = "ml", CategoryId = 4, Description = "Ketjap is een zoete dikke, stroperige, zoete saus die wordt gebruikt in de Indonesische keuken. De saus is gemaakt van sojabonen. Om de saus de zoete authentieke Indonesische smaak te geven wordt er suiker aan toegevoegd." },
             new Ingredient() { Name = "Suiker", Price = 1.20m, Quantity = 1500, Unit = "gram", CategoryId = 4 },
             new Ingredient() { Name = "Tomatensaus", Price = 2.10m, Quantity = 690, Unit = "gram", CategoryId = 4 },
             new Ingredient() { Name = "Water", Price = 1, Quantity = 1, Unit = "liter", CategoryId = 4 },
             new Ingredient() { Name = "Zout", Price = 1, Quantity = 500, Unit = "gram", CategoryId = 4 },
             new Ingredient() { Name = "Forel", Price = 6.45m, Quantity = 425, Unit = "gram", CategoryId = 5, Description = "Deze regenboogforel is een zalmachtige zoetwatervis met een fijne structuur en een lekkere, vrij neutrale smaak." },
             new Ingredient() { Name = "Garnalen", Price = 2.20m, Quantity = 100, Unit = "gram", CategoryId = 5, Description = "Garnalen voor de meest uiteenlopende maaltijden van pasta, paella, currymaaltijd tot een klassieke garnalencocktail een klassieke garnalencocktail met ijsbergsla, whiskey saus en een schijfje citroen." },
             new Ingredient() { Name = "Makreel", Price = 3.30m, Quantity = 350, Unit = "gram", CategoryId = 5, Description = "Goudgele, makreel, warm gerookt op beukenhout (FSC)" },
             new Ingredient() { Name = "Tong", Price = 2.25m, Quantity = 300, Unit = "gram", CategoryId = 5, Description = "Haringfilet, koud gerookt op beukenhout (FSC)" },
             new Ingredient() { Name = "Tonijn", Price = 2.15m, Quantity = 160, Unit = "gram", CategoryId = 5, Description = "Heerlijke stukken tonijn in water." },
             new Ingredient() { Name = "Zalm", Price = 4.35m, Quantity = 160, Unit = "gram", CategoryId = 5, Description = "Stevige zalmfilet uit het koele, zuivere water van de Noorse fjorden. Lekker, veelzijdig en gemakkelijk klaar te maken in koekenpan, oven of op de BBQ of grill." },
             new Ingredient() { Name = "Braadworst", Price = 2.25m, Quantity = 4, Unit = "stuks", CategoryId = 6, Description = "Sappige braadworst, gekruid met een lekkere specerijenmix, dus klaar voor bereiding. Lekker in plakjes gesneden door een bonenschotel en altijd goed met groente en aardappelen, maar probeer ook eens op een broodje met mosterdsaus." },
             new Ingredient() { Name = "Karbonade", Price = 3.50m, Quantity = 360, Unit = "gram", CategoryId = 6, Description = "Gesneden van de schouder van het varken. Iets meer doorregen en iets grover van structuur dan de ribkarbonade. Daarom ook erg geschikt om te stoven of te smoren. Lekker met aardappelen en groente." },
             new Ingredient() { Name = "Knakworst", Price = 2.20m, Quantity = 11, Unit = "stuks", CategoryId = 6 },
             new Ingredient() { Name = "Slavink", Price = 2.20m, Quantity = 3, Unit = "stuks", CategoryId = 6, Description = "Mild gekruid gehakt, omwikkeld met een lapje mager spek, klaar voor de koekenpan. Een smakelijk stukje vlees voor elke dag. Een goede combinatie met pesto-aardappelen en sperziebonen." },
             new Ingredient() { Name = "Spek", Price = 2.10m, Quantity = 150, Unit = "gram", CategoryId = 6, Description = "Rauw, licht gezouten en gerookte spek. Lekker op een broodje of om samen met een eitje in de pan te bakken." },
             new Ingredient() { Name = "Varkensgehakt", Price = 3, Quantity = 500, Unit = "gram", CategoryId = 6, Description = "Half-om-half gehakt om eindeloos mee te variëren. Van gehaktbal, kleine snackballetjes of soepballetjes tot rul gebakken in ovenschotels en pastasaus." },
             new Ingredient() { Name = "Biefstuk", Price = 5.10m, Quantity = 320, Unit = "gram", CategoryId = 6, Description = "Kogelbiefstukken zijn zeer mals met een fijne structuur: pure verwennerij voor vleesliefhebbers. Rood/ Medium bereiding geeft een meer mals en sappiger smaakbeleving. Een feestje met champignons en rode wijn." },
             new Ingredient() { Name = "Hamblokjes", Price = 2.05m, Quantity = 250, Unit = "gram", CategoryId = 6 },
             new Ingredient() { Name = "Hamburger", Price = 3.20m, Quantity = 4, Unit = "stuks", CategoryId = 6, Description = "Hamburgers gemaakt van mild gekruid rundvlees met een rulle structuur. Een smakelijk stukje vlees voor bij de Hollandse maaltijd en een topper op een broodje met sla, tomaat en ui." },
             new Ingredient() { Name = "Rundergehakt", Price = 2.35m, Quantity = 300, Unit = "gram", CategoryId = 6, Description = "Rundergehakt om eindeloos mee te variëren. Natuurlijk voor een gewone gehaktbal, maar ook voor snackballetjes of soepballetjes. Of gebruik het geruld in pastasaus en ovengerechten." },
             new Ingredient() { Name = "Tartaar", Price = 2.10m, Quantity = 2, Unit = "stuks", CategoryId = 6, Description = "Malse rundertartaartjes, gemaakt van zeer mager fijngehakt vlees, dus puur van smaak. Lekker met bloemkool en een romige saus." },
             new Ingredient() { Name = "Tournedos", Price = 3.45m, Quantity = 250, Unit = "gram", CategoryId = 6 },
             new Ingredient() { Name = "Kalkoenfilet", Price = 4.05m, Quantity = 270, Unit = "gram", CategoryId = 6, Description = "Klaar à la minute! Heerlijk mals kalkoenfilet gesneden in plakjes voor het eenvoudig bereiden van de meest uiteenlopende recepten, van nasi goreng tot wraps." },
             new Ingredient() { Name = "Kipfilet", Price = 3.35m, Quantity = 2, Unit = "stuks", CategoryId = 6, Description = "Kipfilet 2x1 stuk in een handige breekverpakking. Zijn 2 stuks te veel? Breek de schaal op de breeklijn in 2 en je kunt het overgebleven deel invriezen." },
             new Ingredient() { Name = "Kippenpoot", Price = 3.25m, Quantity = 8, Unit = "stuks", CategoryId = 6 },
             new Ingredient() { Name = "Kipschnitsel", Price = 2.35m, Quantity = 2, Unit = "stuks", CategoryId = 6, Description = "Kipschnitzel gepaneerd met een geel-oranje panade en voorgegaard." },
             new Ingredient() { Name = "Lamskoteletten", Price = 7, Quantity = 4, Unit = "stuks", CategoryId = 6, Description = "De lamskotelet is de malse karbonade van het lam, gesneden van het ribstuk. Heerlijk met salsa en gepofte aardappel. Kruid eens met rozemarijn." },
             new Ingredient() { Name = "Shoarma", Price = 3.60m, Quantity = 500, Unit = "gram", CategoryId = 6, Description = "Malse reepjes varkensschoudervlees, gekruid met shoarmaspecerijen. Natuurlijk lekker met een broodje, sla en knoflooksaus, maar ook lekker snel klaar met wokgroente en rijst." });

            context.SaveChanges();
        }
    }
}
